"""restored started_at_moscow_time column

Revision ID: 951bced0327f
Revises: cabf424c94bc
Create Date: 2025-05-08 05:45:48.328100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "951bced0327f"
down_revision: Union[str, None] = "cabf424c94bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("started_at_moscow_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "started_at_moscow_time")
    # ### end Alembic commands ###
