"""add colimns total_earned_XP, hide_phone_forma and remove frod_count

Revision ID: 0543c9baa782
Revises:
Create Date: 2025-05-18 05:14:59.435770

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0543c9baa782"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "couriers", sa.Column("total_earned_XP", sa.Float(), nullable=True)
    )
    op.drop_column("global_settings", "frod_count")
    op.add_column(
        "orders",
        sa.Column(
            "hide_phone_forma",
            sa.LargeBinary(),
            server_default=sa.text("E'\\\\x00'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "hide_phone_forma")
    op.add_column(
        "global_settings",
        sa.Column(
            "frod_count", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("couriers", "total_earned_XP")
    # ### end Alembic commands ###
