"""add 2 check tables

Revision ID: 2f034d45f0c7
Revises: 53f413c4fe7a
Create Date: 2025-06-02 16:57:32.649113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f034d45f0c7"
down_revision: Union[str, None] = "53f413c4fe7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courier_clicks",
        sa.Column("click_id", sa.Integer(), nullable=False),
        sa.Column("courier_tg_id", sa.BigInteger(), nullable=True),
        sa.Column("click_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("click_id"),
        sa.UniqueConstraint("courier_tg_id"),
    )
    op.create_table(
        "customer_clicks",
        sa.Column("click_id", sa.Integer(), nullable=False),
        sa.Column("customer_tg_id", sa.BigInteger(), nullable=True),
        sa.Column("click_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("click_id"),
        sa.UniqueConstraint("customer_tg_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("customer_clicks")
    op.drop_table("courier_clicks")
    # ### end Alembic commands ###
