"""add server_default=text(0.0) at total_XP_earned

Revision ID: e664eb9c5aa4
Revises: 0543c9baa782
Create Date: 2025-05-18 09:31:58.573660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e664eb9c5aa4"
down_revision: Union[str, None] = "0543c9baa782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
