"""frod_orders_count create

Revision ID: cdd2115d29bb
Revises: 43ec9a813741
Create Date: 2025-05-06 01:16:17.646316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cdd2115d29bb"
down_revision: Union[str, None] = "43ec9a813741"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "global_settings",
        sa.Column("frod_orders_count", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("global_settings", "frod_orders_count")
    # ### end Alembic commands ###
