"""Change tg_id to BigInteger

Revision ID: af9d592ba74a
Revises: 951bced0327f
Create Date: 2025-05-09 17:54:35.596258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af9d592ba74a"
down_revision: Union[str, None] = "951bced0327f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins",
        "admin_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "couriers",
        "courier_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('couriers_courier_id_seq'::regclass)"
        ),
    )
    op.alter_column(
        "customers",
        "customer_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('customers_customer_id_seq'::regclass)"
        ),
    )
    op.alter_column(
        "partners",
        "partner_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('partners_partner_id_seq'::regclass)"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "partners",
        "partner_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('partners_partner_id_seq'::regclass)"
        ),
    )
    op.alter_column(
        "customers",
        "customer_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('customers_customer_id_seq'::regclass)"
        ),
    )
    op.alter_column(
        "couriers",
        "courier_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text(
            "nextval('couriers_courier_id_seq'::regclass)"
        ),
    )
    op.alter_column(
        "admins",
        "admin_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
