"""add cancelled_at_moscow_time orders

Revision ID: 6d830d69c2c4
Revises: cdd2115d29bb
Create Date: 2025-05-08 04:32:19.735148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d830d69c2c4"
down_revision: Union[str, None] = "cdd2115d29bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("cancelled_at_moscow_time", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "cancelled_at_moscow_time")
    # ### end Alembic commands ###
