"""init

Revision ID: 85363ff022db
Revises:
Create Date: 2025-05-19 14:49:28.159858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85363ff022db"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins",
        "admin_tg_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "earn_requests",
        "partner_tg_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=False,
    )
    op.drop_constraint(
        "earn_requests_partner_tg_id_key", "earn_requests", type_="unique"
    )
    op.alter_column(
        "orders",
        "customer_tg_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=False,
    )
    op.alter_column(
        "orders",
        "courier_tg_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "courier_tg_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "orders",
        "customer_tg_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.create_unique_constraint(
        "earn_requests_partner_tg_id_key", "earn_requests", ["partner_tg_id"]
    )
    op.alter_column(
        "earn_requests",
        "partner_tg_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "admins",
        "admin_tg_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
