"""fix float xp to 2

Revision ID: 53f413c4fe7a
Revises: 85363ff022db
Create Date: 2025-05-22 08:26:11.691610

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53f413c4fe7a"
down_revision: Union[str, None] = "85363ff022db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "couriers",
        "courier_XP",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "couriers",
        "total_earned_XP",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=10, scale=2),
        existing_nullable=True,
        existing_server_default=sa.text("0.0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "couriers",
        "total_earned_XP",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
        existing_server_default=sa.text("0.0"),
    )
    op.alter_column(
        "couriers",
        "courier_XP",
        existing_type=sa.Numeric(precision=10, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
