"""activation_seed_date2

Revision ID: 43ec9a813741
Revises:
Create Date: 2025-05-05 23:08:14.597674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43ec9a813741"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "couriers",
        sa.Column("activation_seed_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "customers",
        sa.Column("activation_seed_date", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "activation_seed_date")
    op.drop_column("couriers", "activation_seed_date")
    # ### end Alembic commands ###
