"""delete frod column

Revision ID: cabf424c94bc
Revises: 0fdf82685319
Create Date: 2025-05-08 05:38:12.270342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cabf424c94bc"
down_revision: Union[str, None] = "0fdf82685319"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("global_settings", "frod_orders_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "global_settings",
        sa.Column(
            "frod_orders_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
