from _dependencies import (
    os,
    enum,
    datetime,
    timedelta,
    Optional,
    Annotated,
    List,
    load_dotenv,
    JSONB,
    ARRAY,
    AsyncAttrs,
    async_sessionmaker,
    create_async_engine,
    Column,
    Integer,
    ForeignKey,
    String,
    BigInteger,
    Enum,
    Boolean,
    DateTime,
    Text,
    Float,
    Date,
    func,
    MetaData,
    text,
    Table,
    JSON,
    Interval,
    Mapped,
    mapped_column,
    DeclarativeBase,
    relationship,
    MappedColumn,
)
from config import db_settings, moscow_time


load_dotenv()

sqlalchemy_url = os.getenv("SQLALCHEMY_URL")
engine = create_async_engine(url=db_settings.DB_URL_asyncpg, echo=False)
async_session_factory = async_sessionmaker(engine)


__all__ = [
    "datetime",
    "timedelta",
    "Optional",
    "Annotated",
    "List",
    "JSONB",
    "ARRAY",
    "AsyncAttrs",
    "async_sessionmaker",
    "create_async_engine",
    "Column",
    "Integer",
    "ForeignKey",
    "String",
    "BigInteger",
    "Enum",
    "enum",
    "Boolean",
    "DateTime",
    "Text",
    "Float",
    "Date",
    "func",
    "MetaData",
    "text",
    "Table",
    "JSON",
    "Interval",
    "Mapped",
    "mapped_column",
    "DeclarativeBase",
    "relationship",
    "MappedColumn",
    "sqlalchemy_url",
    "engine",
    "async_session_factory",
    "moscow_time",
]
